export const countryNameList =
  //   [
  //   { name: 'Afghanistan', alpha2: ' AF', alpha3: 'AFG' },
  //   { name: 'Albania', alpha2: 'AL', alpha3: 'ALB' },
  //   { name: 'Algeria', alpha2: 'DZ', alpha3: 'DZA' },
  //   { name: 'American Samoa', alpha2: 'AS', alpha3: 'ASM' },
  //   { name: 'Andorra', alpha2: 'AD', alpha3: 'AND' },
  //   { name: 'Angola', alpha2: 'AO', alpha3: 'AGO' },
  //   { name: 'Anguilla', alpha2: 'AI', alpha3: 'AIA' },
  //   { name: 'Antigua and Barbuda', alpha2: 'AG', alpha3: 'ATG' },
  //   { name: 'Argentina', alpha2: 'AR', alpha3: 'ARG' },
  //   { name: 'Armenia', alpha2: 'AM', alpha3: 'ARM' },
  //   { name: 'Aruba', alpha2: 'AW', alpha3: 'ABW' },
  //   { name: 'Australia', alpha2: 'AU', alpha3: 'AUS' },
  //   { name: 'Austria', alpha2: 'AT', alpha3: 'AUT' },
  //   { name: 'Azerbaijan', alpha2: 'AZ', alpha3: 'AZE' },
  //   { name: 'Bahamas', alpha2: 'BS', alpha3: 'BHS' },
  //   { name: 'Bahrain', alpha2: 'BH', alpha3: 'BHR' },
  //   { name: 'Bangladesh', alpha2: 'BD', alpha3: 'BGD' },
  //   { name: 'Barbados', alpha2: 'BB', alpha3: 'BRB' },
  //   { name: 'Belarus', alpha2: 'BY', alpha3: 'BLR' },
  //   { name: 'Belgium', alpha2: 'BE', alpha3: 'BEL' },
  //   { name: 'Belize', alpha2: 'BZ', alpha3: 'BLZ' },
  //   { name: 'Benin', alpha2: 'BJ', alpha3: 'BEN' },
  //   { name: 'Bermuda', alpha2: 'BM', alpha3: 'BMU' },
  //   { name: 'Bhutan', alpha2: 'BT', alpha3: 'BTN' },
  //   { name: 'Bolivia', alpha2: 'BO', alpha3: 'BOL' },
  //   { name: 'Bosnia and Herzegovina', alpha2: 'BA', alpha3: 'BIH' },
  //   { name: 'Botswana', alpha2: 'BW', alpha3: 'BWA' },
  //   { name: 'Brazil', alpha2: 'BR', alpha3: 'BRA' },
  //   { name: 'British Virgin Islands', alpha2: 'VG', alpha3: 'VGB' },
  //   { name: 'Brunei Darussalam', alpha2: 'BN', alpha3: 'BRN' },
  //   { name: 'Bulgaria', alpha2: 'BG', alpha3: 'BGR' },
  //   { name: 'Burkina Faso', alpha2: 'BF', alpha3: 'BFA' },
  //   { name: 'Burundi', alpha2: 'BI', alpha3: 'BDI' },
  //   { name: 'Cambodia', alpha2: 'KH', alpha3: 'KHM' },
  //   { name: 'Cameroon', alpha2: 'CM', alpha3: 'CMR' },
  //   { name: 'Canada', alpha2: 'CA', alpha3: 'CAN' },
  //   { name: 'Cape Verde', alpha2: 'CV', alpha3: 'CPV' },
  //   { name: 'Central African Republic', alpha2: 'CF', alpha3: 'CAF' },
  //   { name: 'Chad', alpha2: 'TD', alpha3: 'TCD' },
  //   { name: 'Chile', alpha2: 'CL', alpha3: 'CHL' },
  //   { name: 'China', alpha2: 'CN', alpha3: 'CHN' },
  //   { name: 'Hong Kong', alpha2: 'HK', alpha3: ' HKG' },
  //   { name: 'Macao', alpha2: 'MO', alpha3: 'MAC' },
  //   { name: 'Colombia', alpha2: 'CO', alpha3: 'COL' },
  //   { name: 'Comoros', alpha2: 'KM', alpha3: 'COM' },
  //   { name: 'Congo', alpha2: 'CG', alpha3: 'COG' },
  //   { name: 'Costa Rica', alpha2: 'CR', alpha3: 'CRI' },
  //   { name: 'Côte d&aposIvoire', alpha2: 'CI', alpha3: 'CIV' },
  //   { name: 'Croatia', alpha2: 'HR', alpha3: 'HRV' },
  //   { name: 'Cuba', alpha2: 'CU', alpha3: 'CUB' },
  //   { name: 'Cyprus', alpha2: 'CY', alpha3: 'CYP' },
  //   { name: 'Czech Republic', alpha2: 'CZ', alpha3: 'CZE' },
  //   { name: 'Denmark', alpha2: 'DK', alpha3: 'DNK' },
  //   { name: 'Djibouti', alpha2: 'DJ', alpha3: 'DJI' },
  //   { name: 'Dominica', alpha2: 'DM', alpha3: 'DMA' },
  //   { name: 'Dominican Republic', alpha2: 'DO', alpha3: 'DOM' },
  //   { name: 'Ecuador', alpha2: 'EC', alpha3: 'ECU' },
  //   { name: 'Egypt', alpha2: 'EG', alpha3: 'EGY' },
  //   { name: 'El Salvador', alpha2: 'SV', alpha3: 'SLV' },
  //   { name: 'Equatorial Guinea', alpha2: 'GQ', alpha3: 'GNQ' },
  //   { name: 'Eritrea', alpha2: 'ER', alpha3: 'ERI' },
  //   { name: 'Estonia', alpha2: 'EE', alpha3: 'EST' },
  //   { name: 'Ethiopia', alpha2: 'ET', alpha3: 'ETH' },
  //   { name: 'European Union', alpha2: 'EU', alpha3: '' },
  //   { name: 'Faroe Islands', alpha2: 'FO', alpha3: 'FRO' },
  //   { name: 'Fiji', alpha2: 'FJ', alpha3: 'FJI' },
  //   { name: 'Finland', alpha2: 'FI', alpha3: 'FIN' },
  //   { name: 'France', alpha2: 'FR', alpha3: 'FRA' },
  //   { name: 'French Guiana', alpha2: 'GF', alpha3: 'GUF' },
  //   { name: 'French Polynesia', alpha2: 'PF', alpha3: 'PYF' },
  //   { name: 'Gabon', alpha2: 'GA', alpha3: 'GAB' },
  //   { name: 'Gambia', alpha2: 'GM', alpha3: 'GMB' },
  //   { name: 'Georgia', alpha2: 'GE', alpha3: 'GEO' },
  //   { name: 'Germany', alpha2: 'DE', alpha3: 'DEU' },
  //   { name: 'Ghana', alpha2: 'GH', alpha3: 'GHA' },
  //   { name: 'Greece', alpha2: 'GR', alpha3: 'GRC' },
  //   { name: 'Greenland', alpha2: 'GL', alpha3: 'GRL' },
  //   { name: 'Grenada', alpha2: 'GD', alpha3: 'GRD' },
  //   { name: 'Guadeloupe', alpha2: 'GP', alpha3: 'GLP' },
  //   { name: 'Guam', alpha2: 'GU', alpha3: 'GUM' },
  //   { name: 'Guatemala', alpha2: 'GT', alpha3: 'GTM' },
  //   { name: 'Guinea-Bissau', alpha2: 'GW', alpha3: 'GNB' },
  //   { name: 'Haiti', alpha2: 'HT', alpha3: 'HTI' },
  //   { name: 'Honduras', alpha2: 'HN', alpha3: 'HND' },
  //   { name: 'Hungry', alpha2: 'HU', alpha3: 'HUN' },
  //   { name: 'Iceland', alpha2: 'IS', alpha3: 'ISL' },
  //   { name: 'India', alpha2: 'IN', alpha3: 'IND' },
  //   { name: 'Indonesia', alpha2: 'ID', alpha3: 'IDN' },
  //   { name: 'Iran (Islamic Republic of)', alpha2: 'IR', alpha3: 'IRN' },
  //   { name: 'Iraq', alpha2: 'IQ', alpha3: 'IRQ' },
  //   { name: 'Ireland', alpha2: 'IE', alpha3: 'IRL' },
  //   { name: 'Israel', alpha2: 'IL', alpha3: 'ISR' },
  //   { name: 'Italy', alpha2: 'IT', alpha3: 'ITA' },
  //   { name: 'Japan', alpha2: 'JP', alpha3: 'JPN' },
  //   { name: 'Jordan', alpha2: 'JO', alpha3: 'JOR' },
  //   { name: 'Kazakhstan', alpha2: 'KZ', alpha3: 'KAZ' },
  //   { name: 'Kenya', alpha2: 'KE', alpha3: 'KEN' },
  //   { name: 'Kiribati', alpha2: 'KI', alpha3: 'KIR' },
  //   { name: 'Korea', alpha2: 'KP', alpha3: 'PRK' },
  //   { name: 'Korea', alpha2: 'KR', alpha3: 'KOR' },
  //   { name: 'Kuwait', alpha2: 'KW', alpha3: 'KWT' },
  //   { name: 'Kyrgyzstan', alpha2: 'KG', alpha3: 'KGZ' },
  //   { name: 'Lao PDR', alpha2: 'LA', alpha3: 'LAO' },
  //   { name: 'Latvia', alpha2: 'LV', alpha3: 'LVA' },
  //   { name: 'Lebanon', alpha2: 'LB', alpha3: 'LBN' },
  //   { name: 'Lesotho', alpha2: 'LS', alpha3: 'LSO' },
  //   { name: 'Liberia', alpha2: 'LR', alpha3: 'LBR' },
  //   { name: 'Libya', alpha2: 'LY', alpha3: 'LBY' },
  //   { name: 'Liechtenstein', alpha2: 'LI', alpha3: 'LIE' },
  //   { name: 'Lithuania', alpha2: 'LT', alpha3: 'LTU' },
  //   { name: 'Luxembourg', alpha2: 'LU', alpha3: 'LUX' },
  //   { name: 'Madagascar', alpha2: 'MG', alpha3: 'MDG' },
  //   { name: 'Malawi', alpha2: 'MW', alpha3: 'MWI' },
  //   { name: 'Malaysia', alpha2: 'MY', alpha3: 'MYS' },
  //   { name: 'Maldives', alpha2: 'MV', alpha3: 'MDV' },
  //   { name: 'Mali', alpha2: 'ML', alpha3: 'MLI' },
  //   { name: 'Malta', alpha2: 'MT', alpha3: 'MLT' },
  //   { name: 'Marshall Islands', alpha2: 'MH', alpha3: 'MHL' },
  //   { name: 'Martinique', alpha2: 'MQ', alpha3: 'MTQ' },
  //   { name: 'Mauritania', alpha2: 'MR', alpha3: 'MRT' },
  //   { name: 'Mauritius', alpha2: 'MU', alpha3: 'MUS' },
  //   { name: 'Mexico', alpha2: 'MX', alpha3: 'MEX' },
  //   { name: 'Micronesia, Federated States of', alpha2: 'FM', alpha3: 'FSM' },
  //   { name: 'Moldova', alpha2: 'MD', alpha3: 'MDA' },
  //   { name: 'Monaco', alpha2: 'MC', alpha3: 'MCO' },
  //   { name: 'Mongolia', alpha2: 'MN', alpha3: 'MNG' },
  //   { name: 'Montenegro', alpha2: 'ME', alpha3: 'MNE' },
  //   { name: 'Montserrat', alpha2: 'MS', alpha3: 'MSR' },
  //   { name: 'Morocco', alpha2: 'MA', alpha3: 'MAR' },
  //   { name: 'Mozambique', alpha2: 'MZ', alpha3: 'MOZ' },
  //   { name: 'Myanmar', alpha2: 'MM', alpha3: 'MMR' },
  //   { name: 'Namibia', alpha2: 'NA', alpha3: 'NAM' },
  //   { name: 'Nauru', alpha2: 'NR', alpha3: 'NRU' },
  //   { name: 'Nepal', alpha2: 'NP', alpha3: 'NPL' },
  //   { name: 'Netherlands', alpha2: 'NL', alpha3: 'NLD' },
  //   { name: 'Netherlands Antilles', alpha2: 'AN', alpha3: 'ANT' },
  //   { name: 'New Caledonia', alpha2: 'NC', alpha3: 'NCL' },
  //   { name: 'New Zealand', alpha2: 'NZ', alpha3: 'NZL' },
  //   { name: 'Nicaragua', alpha2: 'NI', alpha3: 'NIC' },
  //   { name: 'Niger', alpha2: 'NE', alpha3: 'NER' },
  //   { name: 'Nigeria', alpha2: 'NG', alpha3: 'NGA' },
  //   { name: 'Northern Mariana Islands', alpha2: 'MP', alpha3: 'MNP' },
  //   { name: 'Norway', alpha2: 'NO', alpha3: 'NOR' },
  //   { name: 'Oman', alpha2: 'OM', alpha3: 'OMN' },
  //   { name: 'Pakistan', alpha2: 'PK', alpha3: 'PAK' },
  //   { name: 'Palau', alpha2: 'PW', alpha3: 'PLW' },
  //   { name: 'Palestinian Territory', alpha2: 'PS', alpha3: 'PSE' },
  //   { name: 'Panama', alpha2: 'PA', alpha3: 'PAN' },
  //   { name: 'Papua New Guinea', alpha2: 'PG', alpha3: 'PNG' },
  //   { name: 'Paraguay', alpha2: 'PY', alpha3: 'PRY' },
  //   { name: 'Peru', alpha2: 'PE', alpha3: 'PER' },
  //   { name: 'Philippines', alpha2: 'PH', alpha3: 'PHL' },
  //   { name: 'Pitcairn', alpha2: 'PN', alpha3: 'PCN' },
  //   { name: 'Poland', alpha2: 'PL', alpha3: 'POL' },
  //   { name: 'Portugal', alpha2: 'PT', alpha3: 'PRT' },
  //   { name: 'Puerto Rico', alpha2: 'PR', alpha3: 'PRI' },
  //   { name: 'Qatar', alpha2: 'QA', alpha3: 'QAT' },
  //   { name: 'Réunion', alpha2: 'RE', alpha3: 'REU' },
  //   { name: 'Romania', alpha2: 'RO', alpha3: 'ROU' },
  //   { name: 'Russian Federation', alpha2: 'RU', alpha3: 'RUS' },
  //   { name: 'Rwanda', alpha2: 'RW', alpha3: 'RWA' },
  //   { name: 'Saint Kitts and Nevis', alpha2: 'KN', alpha3: 'KNA' },
  //   { name: 'Saint Lucia', alpha2: 'LC', alpha3: 'LCA' },
  //   { name: 'Saint Vincent and Grenadines', alpha2: 'VC', alpha3: 'VCT' },
  //   { name: 'Samoa', alpha2: 'WS', alpha3: 'WSM' },
  //   { name: 'San Marino', alpha2: 'SM', alpha3: 'SMR' },
  //   { name: 'Sao Tome and Principe', alpha2: 'ST', alpha3: 'STP' },
  //   { name: 'Saudi Arabia', alpha2: 'SA', alpha3: 'SAU' },
  //   { name: 'Senegal', alpha2: 'SN', alpha3: 'SEN' },
  //   { name: 'Serbia', alpha2: 'RS', alpha3: 'SRB' },
  //   { name: 'Seychelles', alpha2: 'SC', alpha3: 'SYC' },
  //   { name: 'Sierra Leone', alpha2: 'SL', alpha3: 'SLE' },
  //   { name: 'Singapore', alpha2: 'SG', alpha3: 'SGP' },
  //   { name: 'Slovakia', alpha2: 'SK', alpha3: 'SVK' },
  //   { name: 'Slovenia', alpha2: 'SI', alpha3: 'SVN' },
  //   { name: 'Solomon Islands', alpha2: 'SB', alpha3: 'SLB' },
  //   { name: 'Somalia', alpha2: 'SO', alpha3: 'SOM' },
  //   { name: 'South Africa', alpha2: 'ZA', alpha3: 'ZAF' },
  //   { name: 'Spain', alpha2: 'ES', alpha3: 'ESP' },
  //   { name: 'Sri Lanka', alpha2: 'LK', alpha3: 'LKA' },
  //   { name: 'Sudan', alpha2: 'SD', alpha3: 'SDN' },
  //   { name: 'Suriname', alpha2: 'SR', alpha3: 'SUR' },
  //   { name: 'Swaziland', alpha2: 'SZ', alpha3: 'SWZ' },
  //   { name: 'Sweden', alpha2: 'SE', alpha3: 'SWE' },
  //   { name: 'Switzerland', alpha2: 'CH', alpha3: 'CHE' },
  //   { name: 'Syrian Arab Republic', alpha2: 'SY', alpha3: 'SYR' },
  //   { name: 'Taiwan (Province of China)', alpha2: 'TW', alpha3: 'TWN' },
  //   { name: 'Tajikistan', alpha2: 'TJ', alpha3: 'TJK' },
  //   { name: 'Tanzania', alpha2: 'TZ', alpha3: 'TZA' },
  //   { name: 'Thailand', alpha2: 'TH', alpha3: 'THA' },
  //   { name: 'Timor-Leste', alpha2: 'TL', alpha3: 'TLS' },
  //   { name: 'Togo', alpha2: 'TG', alpha3: 'TGO' },
  //   { name: 'Tonga', alpha2: 'TO', alpha3: 'TON' },
  //   { name: 'Trinidad and Tobago', alpha2: 'TT', alpha3: 'TTO' },
  //   { name: 'Tunisia', alpha2: 'TN', alpha3: 'TUN' },
  //   { name: 'Turkey', alpha2: 'TR', alpha3: 'TUR' },
  //   { name: 'Turkmenistan', alpha2: 'TM', alpha3: 'TKM' },
  //   { name: 'Tuvalu', alpha2: 'TV', alpha3: 'TUV' },
  //   { name: 'Uganda', alpha2: 'UG', alpha3: 'UGA' },
  //   { name: 'Ukraine', alpha2: 'UA', alpha3: 'UKR' },
  //   { name: 'United Arab Emirates', alpha2: 'AE', alpha3: 'ARE' },
  //   { name: 'United Kingdom', alpha2: 'GB', alpha3: 'GBR' },
  //   { name: 'United States of America', alpha2: 'US', alpha3: 'USA' },
  //   { name: 'Uruguay', alpha2: 'UY', alpha3: 'URY' },
  //   { name: 'Uzbekistan', alpha2: 'UZ', alpha3: 'UZB' },
  //   { name: 'Vanuatu', alpha2: 'VU', alpha3: 'VUT' },
  //   { name: 'Venezuela', alpha2: 'VE', alpha3: 'VEN' },
  //   { name: 'Viet Nam', alpha2: 'VN', alpha3: 'VNM' },
  //   { name: 'Virgin Islands, US', alpha2: 'VI', alpha3: 'VIR' },
  //   { name: 'Yemen', alpha2: 'YE', alpha3: 'YEM' },
  //   { name: 'Zambia', alpha2: 'ZM', alpha3: 'ZMB' },
  //   { name: 'Zimbabwe', alpha2: 'ZW', alpha3: 'ZWE' },
  // ];
  [
    { name: 'United Kingdom', flag: '🇬🇧', code: 'GB', dial_code: '+44' },
    { name: 'International', flag: '🌎', code: 'INT', dial_code: '+44' },
    { name: 'USA', flag: '🇺🇸', code: 'US', dial_code: '+1' },
    { name: 'Afghanistan', flag: '🇦🇫', code: 'AF', dial_code: '+93' },
    { name: 'Åland Islands', flag: '🇦🇽', code: 'AX', dial_code: '+358' },
    { name: 'Albania', flag: '🇦🇱', code: 'AL', dial_code: '+355' },
    { name: 'Algeria', flag: '🇩🇿', code: 'DZ', dial_code: '+213' },
    { name: 'American Samoa', flag: '🇦🇸', code: 'AS', dial_code: '+1684' },
    { name: 'Andorra', flag: '🇦🇩', code: 'AD', dial_code: '+376' },
    { name: 'Angola', flag: '🇦🇴', code: 'AO', dial_code: '+244' },
    { name: 'Anguilla', flag: '🇦🇮', code: 'AI', dial_code: '+1264' },
    { name: 'Antarctica', flag: '🇦🇶', code: 'AQ', dial_code: '+672' },
    { name: 'Antigua and Barbuda', flag: '🇦🇬', code: 'AG', dial_code: '+1268' },
    { name: 'Argentina', flag: '🇦🇷', code: 'AR', dial_code: '+54' },
    { name: 'Armenia', flag: '🇦🇲', code: 'AM', dial_code: '+374' },
    { name: 'Aruba', flag: '🇦🇼', code: 'AW', dial_code: '+297' },
    { name: 'Australia', flag: '🇦🇺', code: 'AU', dial_code: '+61' },
    { name: 'Austria', flag: '🇦🇹', code: 'AT', dial_code: '+43' },
    { name: 'Austria Amateur', flag: '🇦🇹', code: 'AT', dial_code: '+43' },
    { name: 'Azerbaijan', flag: '🇦🇿', code: 'AZ', dial_code: '+994' },
    { name: 'Bahamas', flag: '🇧🇸', code: 'BS', dial_code: '+1242' },
    { name: 'Bahrain', flag: '🇧🇭', code: 'BH', dial_code: '+973' },
    { name: 'Bangladesh', flag: '🇧🇩', code: 'BD', dial_code: '+880' },
    { name: 'Barbados', flag: '🇧🇧', code: 'BB', dial_code: '+1246' },
    { name: 'Belarus', flag: '🇧🇾', code: 'BY', dial_code: '+375' },
    { name: 'Belgium', flag: '🇧🇪', code: 'BE', dial_code: '+32' },
    { name: 'Belize', flag: '🇧🇿', code: 'BZ', dial_code: '+501' },
    { name: 'Benin', flag: '🇧🇯', code: 'BJ', dial_code: '+229' },
    { name: 'Bermuda', flag: '🇧🇲', code: 'BM', dial_code: '+1441' },
    { name: 'Bhutan', flag: '🇧🇹', code: 'BT', dial_code: '+975' },
    {
      name: 'Bolivia, Plurinational State of bolivia',
      flag: '🇧🇴',
      code: 'BO',
      dial_code: '+591',
    },
    {
      name: 'Bolivia',
      flag: '🇧🇴',
      code: 'BO',
      dial_code: '+591',
    },
    { name: 'Bosnia & Herzegovina', flag: '🇧🇦', code: 'BA', dial_code: '+387' },
    { name: 'Botswana', flag: '🇧🇼', code: 'BW', dial_code: '+267' },
    { name: 'Bouvet Island', flag: '🇧🇻', code: 'BV', dial_code: '+47' },
    { name: 'Brazil', flag: '🇧🇷', code: 'BR', dial_code: '+55' },
    {
      name: 'British Indian Ocean Territory',
      flag: '🇮🇴',
      code: 'IO',
      dial_code: '+246',
    },
    { name: 'Brunei Darussalam', flag: '🇧🇳', code: 'BN', dial_code: '+673' },
    { name: 'Bulgaria', flag: '🇧🇬', code: 'BG', dial_code: '+359' },
    { name: 'Burkina Faso', flag: '🇧🇫', code: 'BF', dial_code: '+226' },
    { name: 'Burundi', flag: '🇧🇮', code: 'BI', dial_code: '+257' },
    { name: 'Cambodia', flag: '🇰🇭', code: 'KH', dial_code: '+855' },
    { name: 'Cameroon', flag: '🇨🇲', code: 'CM', dial_code: '+237' },
    { name: 'Canada', flag: '🇨🇦', code: 'CA', dial_code: '+1' },
    { name: 'Cape Verde', flag: '🇨🇻', code: 'CV', dial_code: '+238' },
    { name: 'Cayman Islands', flag: '🇰🇾', code: 'KY', dial_code: '+345' },
    {
      name: 'Central African Republic',
      flag: '🇨🇫',
      code: 'CF',
      dial_code: '+236',
    },
    { name: 'Chad', flag: '🇹🇩', code: 'TD', dial_code: '+235' },
    { name: 'Chile', flag: '🇨🇱', code: 'CL', dial_code: '+56' },
    { name: 'China', flag: '🇨🇳', code: 'CN', dial_code: '+86' },
    { name: 'Christmas Island', flag: '🇨🇽', code: 'CX', dial_code: '+61' },
    {
      name: 'Cocos (Keeling) Islands',
      flag: '🇨🇨',
      code: 'CC',
      dial_code: '+61',
    },
    { name: 'Colombia', flag: '🇨🇴', code: 'CO', dial_code: '+57' },
    { name: 'Comoros', flag: '🇰🇲', code: 'KM', dial_code: '+269' },
    { name: 'Congo', flag: '🇨🇬', code: 'CG', dial_code: '+242' },
    {
      name: 'Congo, The Democratic Republic of the Congo',
      flag: '🇨🇩',
      code: 'CD',
      dial_code: '+243',
    },
    { name: 'Cook Islands', flag: '🇨🇰', code: 'CK', dial_code: '+682' },
    { name: 'Costa Rica', flag: '🇨🇷', code: 'CR', dial_code: '+506' },
    { name: 'Cote dIvoire', flag: '🇨🇮', code: 'CI', dial_code: '+225' },
    { name: 'Croatia', flag: '🇭🇷', code: 'HR', dial_code: '+385' },
    { name: 'Cuba', flag: '🇨🇺', code: 'CU', dial_code: '+53' },
    { name: 'Cyprus', flag: '🇨🇾', code: 'CY', dial_code: '+357' },
    { name: 'Czech Republic', flag: '🇨🇿', code: 'CZ', dial_code: '+420' },
    { name: 'Denmark', flag: '🇩🇰', code: 'DK', dial_code: '+45' },
    { name: 'Denmark Amateur', flag: '🇩🇰', code: 'DK', dial_code: '+45' },

    { name: 'Djibouti', flag: '🇩🇯', code: 'DJ', dial_code: '+253' },
    { name: 'Dominica', flag: '🇩🇲', code: 'DM', dial_code: '+1767' },
    { name: 'Dominican Republic', flag: '🇩🇴', code: 'DO', dial_code: '+1849' },
    { name: 'Ecuador', flag: '🇪🇨', code: 'EC', dial_code: '+593' },
    { name: 'Egypt', flag: '🇪🇬', code: 'EG', dial_code: '+20' },
    { name: 'El Salvador', flag: '🇸🇻', code: 'SV', dial_code: '+503' },
    { name: 'Equatorial Guinea', flag: '🇬🇶', code: 'GQ', dial_code: '+240' },
    { name: 'Eritrea', flag: '🇪🇷', code: 'ER', dial_code: '+291' },
    { name: 'Estonia', flag: '🇪🇪', code: 'EE', dial_code: '+372' },
    { name: 'Ethiopia', flag: '🇪🇹', code: 'ET', dial_code: '+251' },
    {
      name: 'Falkland Islands (Malvinas)',
      flag: '🇫🇰',
      code: 'FK',
      dial_code: '+500',
    },
    { name: 'Faroe Islands', flag: '🇫🇴', code: 'FO', dial_code: '+298' },
    { name: 'Fiji', flag: '🇫🇯', code: 'FJ', dial_code: '+679' },
    { name: 'Finland', flag: '🇫🇮', code: 'FI', dial_code: '+358' },
    { name: 'France', flag: '🇫🇷', code: 'FR', dial_code: '+33' },
    { name: 'French Guiana', flag: '🇬🇫', code: 'GF', dial_code: '+594' },
    { name: 'French Polynesia', flag: '🇵🇫', code: 'PF', dial_code: '+689' },
    {
      name: 'French Southern Territories',
      flag: '🇹🇫',
      code: 'TF',
      dial_code: '+262',
    },
    { name: 'Gabon', flag: '🇬🇦', code: 'GA', dial_code: '+241' },
    { name: 'Gambia', flag: '🇬🇲', code: 'GM', dial_code: '+220' },
    { name: 'Georgia', flag: '🇬🇪', code: 'GE', dial_code: '+995' },
    { name: 'Germany', flag: '🇩🇪', code: 'DE', dial_code: '+49' },
    { name: 'Germany Amateur', flag: '🇩🇪', code: 'DE', dial_code: '+49' },
    { name: 'Ghana', flag: '🇬🇭', code: 'GH', dial_code: '+233' },
    { name: 'Gibraltar', flag: '🇬🇮', code: 'GI', dial_code: '+350' },
    { name: 'Greece', flag: '🇬🇷', code: 'GR', dial_code: '+30' },
    { name: 'Greenland', flag: '🇬🇱', code: 'GL', dial_code: '+299' },
    { name: 'Grenada', flag: '🇬🇩', code: 'GD', dial_code: '+1473' },
    { name: 'Guadeloupe', flag: '🇬🇵', code: 'GP', dial_code: '+590' },
    { name: 'Guam', flag: '🇬🇺', code: 'GU', dial_code: '+1671' },
    { name: 'Guatemala', flag: '🇬🇹', code: 'GT', dial_code: '+502' },
    { name: 'Guernsey', flag: '🇬🇬', code: 'GG', dial_code: '+44' },
    { name: 'Guinea', flag: '🇬🇳', code: 'GN', dial_code: '+224' },
    { name: 'Guinea-Bissau', flag: '🇬🇼', code: 'GW', dial_code: '+245' },
    { name: 'Guyana', flag: '🇬🇾', code: 'GY', dial_code: '+592' },
    { name: 'Haiti', flag: '🇭🇹', code: 'HT', dial_code: '+509' },
    {
      name: 'Heard Island and Mcdonald Islands',
      flag: '🇭🇲',
      code: 'HM',
      dial_code: '+672',
    },
    {
      name: 'Holy See (Vatican City State)',
      flag: '🇻🇦',
      code: 'VA',
      dial_code: '+379',
    },
    { name: 'Honduras', flag: '🇭🇳', code: 'HN', dial_code: '+504' },
    { name: 'Hong Kong, China', flag: '🇭🇰', code: 'HK', dial_code: '+852' },
    { name: 'Hungary', flag: '🇭🇺', code: 'HU', dial_code: '+36' },
    { name: 'Iceland', flag: '🇮🇸', code: 'IS', dial_code: '+354' },
    { name: 'India', flag: '🇮🇳', code: 'IN', dial_code: '+91' },
    { name: 'Indonesia', flag: '🇮🇩', code: 'ID', dial_code: '+62' },
    {
      name: 'Iran',
      flag: '🇮🇷',
      code: 'IR',
      dial_code: '+98',
    },
    { name: 'Iraq', flag: '🇮🇶', code: 'IQ', dial_code: '+964' },
    { name: 'Northern Ireland', flag: '🇮🇪', code: 'IE', dial_code: '+353' },
    { name: 'Ireland', flag: '🇮🇪', code: 'IE', dial_code: '+353' },
    { name: 'Isle of Man', flag: '🇮🇲', code: 'IM', dial_code: '+44' },
    { name: 'Israel', flag: '🇮🇱', code: 'IL', dial_code: '+972' },
    { name: 'Italy', flag: '🇮🇹', code: 'IT', dial_code: '+39' },
    { name: 'Jamaica', flag: '🇯🇲', code: 'JM', dial_code: '+1876' },
    { name: 'Japan', flag: '🇯🇵', code: 'JP', dial_code: '+81' },
    { name: 'Jersey', flag: '🇯🇪', code: 'JE', dial_code: '+44' },
    { name: 'Jordan', flag: '🇯🇴', code: 'JO', dial_code: '+962' },
    { name: 'Kazakhstan', flag: '🇰🇿', code: 'KZ', dial_code: '+7' },
    { name: 'Kenya', flag: '🇰🇪', code: 'KE', dial_code: '+254' },
    { name: 'Kiribati', flag: '🇰🇮', code: 'KI', dial_code: '+686' },
    {
      name: 'Republic of Korea',
      flag: '🇰🇵',
      code: 'KP',
      dial_code: '+850',
    },
    {
      name: 'Korea, Republic of South Korea',
      flag: '🇰🇷',
      code: 'KR',
      dial_code: '+82',
    },
    { name: 'Kosovo', flag: '🇽🇰', code: 'XK', dial_code: '+383' },
    { name: 'Kuwait', flag: '🇰🇼', code: 'KW', dial_code: '+965' },
    { name: 'Kyrgyzstan', flag: '🇰🇬', code: 'KG', dial_code: '+996' },
    { name: 'Laos', flag: '🇱🇦', code: 'LA', dial_code: '+856' },
    { name: 'Latvia', flag: '🇱🇻', code: 'LV', dial_code: '+371' },
    { name: 'Lebanon', flag: '🇱🇧', code: 'LB', dial_code: '+961' },
    { name: 'Lesotho', flag: '🇱🇸', code: 'LS', dial_code: '+266' },
    { name: 'Liberia', flag: '🇱🇷', code: 'LR', dial_code: '+231' },
    {
      name: 'Libyan Arab Jamahiriya',
      flag: '🇱🇾',
      code: 'LY',
      dial_code: '+218',
    },
    { name: 'Liechtenstein', flag: '🇱🇮', code: 'LI', dial_code: '+423' },
    { name: 'Lithuania', flag: '🇱🇹', code: 'LT', dial_code: '+370' },
    { name: 'Luxembourg', flag: '🇱🇺', code: 'LU', dial_code: '+352' },
    { name: 'Macao', flag: '🇲🇴', code: 'MO', dial_code: '+853' },
    { name: 'Macedonia', flag: '🇲🇰', code: 'MK', dial_code: '+389' },
    { name: 'North Macedonia', flag: '🇲🇰', code: 'MK', dial_code: '+389' },

    { name: 'Madagascar', flag: '🇲🇬', code: 'MG', dial_code: '+261' },
    { name: 'Malawi', flag: '🇲🇼', code: 'MW', dial_code: '+265' },
    { name: 'Malaysia', flag: '🇲🇾', code: 'MY', dial_code: '+60' },
    { name: 'Maldives', flag: '🇲🇻', code: 'MV', dial_code: '+960' },
    { name: 'Mali', flag: '🇲🇱', code: 'ML', dial_code: '+223' },
    { name: 'Malta', flag: '🇲🇹', code: 'MT', dial_code: '+356' },
    { name: 'Marshall Islands', flag: '🇲🇭', code: 'MH', dial_code: '+692' },
    { name: 'Martinique', flag: '🇲🇶', code: 'MQ', dial_code: '+596' },
    { name: 'Mauritania', flag: '🇲🇷', code: 'MR', dial_code: '+222' },
    { name: 'Mauritius', flag: '🇲🇺', code: 'MU', dial_code: '+230' },
    { name: 'Mayotte', flag: '🇾🇹', code: 'YT', dial_code: '+262' },
    { name: 'Mexico', flag: '🇲🇽', code: 'MX', dial_code: '+52' },
    {
      name: 'Micronesia, Federated States of Micronesia',
      flag: '🇫🇲',
      code: 'FM',
      dial_code: '+691',
    },
    { name: 'Moldova', flag: '🇲🇩', code: 'MD', dial_code: '+373' },
    { name: 'Monaco', flag: '🇲🇨', code: 'MC', dial_code: '+377' },
    { name: 'Mongolia', flag: '🇲🇳', code: 'MN', dial_code: '+976' },
    { name: 'Montenegro', flag: '🇲🇪', code: 'ME', dial_code: '+382' },
    { name: 'Montserrat', flag: '🇲🇸', code: 'MS', dial_code: '+1664' },
    { name: 'Morocco', flag: '🇲🇦', code: 'MA', dial_code: '+212' },
    { name: 'Mozambique', flag: '🇲🇿', code: 'MZ', dial_code: '+258' },
    { name: 'Myanmar', flag: '🇲🇲', code: 'MM', dial_code: '+95' },
    { name: 'Namibia', flag: '🇳🇦', code: 'NA', dial_code: '+264' },
    { name: 'Nauru', flag: '🇳🇷', code: 'NR', dial_code: '+674' },
    { name: 'Nepal', flag: '🇳🇵', code: 'NP', dial_code: '+977' },
    { name: 'Netherlands', flag: '🇳🇱', code: 'NL', dial_code: '+31' },
    { name: 'Netherlands Antilles', flag: '', code: 'AN', dial_code: '+599' },
    { name: 'New Caledonia', flag: '🇳🇨', code: 'NC', dial_code: '+687' },
    { name: 'New Zealand', flag: '🇳🇿', code: 'NZ', dial_code: '+64' },
    { name: 'Nicaragua', flag: '🇳🇮', code: 'NI', dial_code: '+505' },
    { name: 'Niger', flag: '🇳🇪', code: 'NE', dial_code: '+227' },
    { name: 'Nigeria', flag: '🇳🇬', code: 'NG', dial_code: '+234' },
    { name: 'Niue', flag: '🇳🇺', code: 'NU', dial_code: '+683' },
    { name: 'Norfolk Island', flag: '🇳🇫', code: 'NF', dial_code: '+672' },
    {
      name: 'Northern Mariana Islands',
      flag: '🇲🇵',
      code: 'MP',
      dial_code: '+1670',
    },
    { name: 'Norway', flag: '🇳🇴', code: 'NO', dial_code: '+47' },
    { name: 'Oman', flag: '🇴🇲', code: 'OM', dial_code: '+968' },
    { name: 'Pakistan', flag: '🇵🇰', code: 'PK', dial_code: '+92' },
    { name: 'Palau', flag: '🇵🇼', code: 'PW', dial_code: '+680' },
    {
      name: 'Palestinian Territory, Occupied',
      flag: '🇵🇸',
      code: 'PS',
      dial_code: '+970',
    },
    { name: 'Panama', flag: '🇵🇦', code: 'PA', dial_code: '+507' },
    { name: 'Papua New Guinea', flag: '🇵🇬', code: 'PG', dial_code: '+675' },
    { name: 'Paraguay', flag: '🇵🇾', code: 'PY', dial_code: '+595' },
    { name: 'Peru', flag: '🇵🇪', code: 'PE', dial_code: '+51' },
    { name: 'Philippines', flag: '🇵🇭', code: 'PH', dial_code: '+63' },
    { name: 'Pitcairn', flag: '🇵🇳', code: 'PN', dial_code: '+64' },
    { name: 'Poland', flag: '🇵🇱', code: 'PL', dial_code: '+48' },
    { name: 'Portugal', flag: '🇵🇹', code: 'PT', dial_code: '+351' },
    { name: 'Puerto Rico', flag: '🇵🇷', code: 'PR', dial_code: '+1939' },
    { name: 'Qatar', flag: '🇶🇦', code: 'QA', dial_code: '+974' },
    { name: 'Romania', flag: '🇷🇴', code: 'RO', dial_code: '+40' },
    { name: 'Russia', flag: '🇷🇺', code: 'RU', dial_code: '+7' },
    { name: 'Rwanda', flag: '🇷🇼', code: 'RW', dial_code: '+250' },
    { name: 'Reunion', flag: '🇷🇪', code: 'RE', dial_code: '+262' },
    { name: 'Saint Barthelemy', flag: '🇧🇱', code: 'BL', dial_code: '+590' },
    {
      name: 'Saint Helena, Ascension and Tristan Da Cunha',
      flag: '🇸🇭',
      code: 'SH',
      dial_code: '+290',
    },
    {
      name: 'Saint Kitts and Nevis',
      flag: '🇰🇳',
      code: 'KN',
      dial_code: '+1869',
    },
    { name: 'Saint Lucia', flag: '🇱🇨', code: 'LC', dial_code: '+1758' },
    { name: 'Saint Martin', flag: '🇲🇫', code: 'MF', dial_code: '+590' },
    {
      name: 'Saint Pierre and Miquelon',
      flag: '🇵🇲',
      code: 'PM',
      dial_code: '+508',
    },
    {
      name: 'Saint Vincent and the Grenadines',
      flag: '🇻🇨',
      code: 'VC',
      dial_code: '+1784',
    },
    { name: 'Samoa', flag: '🇼🇸', code: 'WS', dial_code: '+685' },
    { name: 'San Marino', flag: '🇸🇲', code: 'SM', dial_code: '+378' },
    {
      name: 'Sao Tome and Principe',
      flag: '🇸🇹',
      code: 'ST',
      dial_code: '+239',
    },
    { name: 'Scotland', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', code: 'ST', dial_code: '+44' },
    { name: 'Saudi Arabia', flag: '🇸🇦', code: 'SA', dial_code: '+966' },
    { name: 'Senegal', flag: '🇸🇳', code: 'SN', dial_code: '+221' },
    { name: 'Serbia', flag: '🇷🇸', code: 'RS', dial_code: '+381' },
    { name: 'Seychelles', flag: '🇸🇨', code: 'SC', dial_code: '+248' },
    { name: 'Sierra Leone', flag: '🇸🇱', code: 'SL', dial_code: '+232' },
    { name: 'Singapore', flag: '🇸🇬', code: 'SG', dial_code: '+65' },
    { name: 'Slovakia', flag: '🇸🇰', code: 'SK', dial_code: '+421' },
    { name: 'Slovenia', flag: '🇸🇮', code: 'SI', dial_code: '+386' },
    { name: 'Solomon Islands', flag: '🇸🇧', code: 'SB', dial_code: '+677' },
    { name: 'Somalia', flag: '🇸🇴', code: 'SO', dial_code: '+252' },
    { name: 'South Africa', flag: '🇿🇦', code: 'ZA', dial_code: '+27' },
    { name: 'South Sudan', flag: '🇸🇸', code: 'SS', dial_code: '+211' },
    {
      name: 'South Georgia and the South Sandwich Islands',
      flag: '🇬🇸',
      code: 'GS',
      dial_code: '+500',
    },
    { name: 'Spain', flag: '🇪🇸', code: 'ES', dial_code: '+34' },
    { name: 'Spain Amateur', flag: '🇪🇸', code: 'ES', dial_code: '+34' },
    { name: 'Sri Lanka', flag: '🇱🇰', code: 'LK', dial_code: '+94' },
    { name: 'Sudan', flag: '🇸🇩', code: 'SD', dial_code: '+249' },
    { name: 'Suriname', flag: '🇸🇷', code: 'SR', dial_code: '+597' },
    {
      name: 'Svalbard and Jan Mayen',
      flag: '🇸🇯',
      code: 'SJ',
      dial_code: '+47',
    },
    { name: 'Eswatini', flag: '🇸🇿', code: 'SZ', dial_code: '+268' },
    { name: 'Sweden', flag: '🇸🇪', code: 'SE', dial_code: '+46' },
    { name: 'Switzerland', flag: '🇨🇭', code: 'CH', dial_code: '+41' },
    { name: 'Syrian Arab Republic', flag: '🇸🇾', code: 'SY', dial_code: '+963' },
    { name: 'Syria', flag: '🇸🇾', code: 'SY', dial_code: '+963' },

    { name: 'Taiwan', flag: '🇹🇼', code: 'TW', dial_code: '+886' },
    { name: 'Chinese Taipei', flag: '🇹🇼', code: 'TW', dial_code: '+886' },

    { name: 'Tajikistan', flag: '🇹🇯', code: 'TJ', dial_code: '+992' },
    {
      name: 'Tanzania',
      flag: '🇹🇿',
      code: 'TZ',
      dial_code: '+255',
    },
    { name: 'Thailand', flag: '🇹🇭', code: 'TH', dial_code: '+66' },
    { name: 'Timor-Leste', flag: '🇹🇱', code: 'TL', dial_code: '+670' },
    { name: 'Togo', flag: '🇹🇬', code: 'TG', dial_code: '+228' },
    { name: 'Tokelau', flag: '🇹🇰', code: 'TK', dial_code: '+690' },
    { name: 'Tonga', flag: '🇹🇴', code: 'TO', dial_code: '+676' },
    { name: 'Trinidad and Tobago', flag: '🇹🇹', code: 'TT', dial_code: '+1868' },
    { name: 'Tunisia', flag: '🇹🇳', code: 'TN', dial_code: '+216' },
    { name: 'Turkey', flag: '🇹🇷', code: 'TR', dial_code: '+90' },

    { name: 'Turkiye', flag: '🇹🇷', code: 'TR', dial_code: '+90' },
    { name: 'Turkiye Amateur', flag: '🇹🇷', code: 'TR', dial_code: '+90' },

    { name: 'Turkmenistan', flag: '🇹🇲', code: 'TM', dial_code: '+993' },
    {
      name: 'Turks and Caicos Islands',
      flag: '🇹🇨',
      code: 'TC',
      dial_code: '+1649',
    },
    { name: 'Tuvalu', flag: '🇹🇻', code: 'TV', dial_code: '+688' },
    { name: 'Uganda', flag: '🇺🇬', code: 'UG', dial_code: '+256' },
    { name: 'Ukraine', flag: '🇺🇦', code: 'UA', dial_code: '+380' },
    { name: 'England', flag: '🇦🇪', code: 'AE', dial_code: '+971' },
    { name: 'England Amateur', flag: '🇦🇪', code: 'AE', dial_code: '+971' },

    { name: 'Uruguay', flag: '🇺🇾', code: 'UY', dial_code: '+598' },
    { name: 'Uzbekistan', flag: '🇺🇿', code: 'UZ', dial_code: '+998' },
    { name: 'Vanuatu', flag: '🇻🇺', code: 'VU', dial_code: '+678' },
    {
      name: 'Venezuela',
      flag: '🇻🇪',
      code: 'VE',
      dial_code: '+58',
    },
    { name: 'Vietnam', flag: '🇻🇳', code: 'VN', dial_code: '+84' },
    {
      name: 'Virgin Islands, British',
      flag: '🇻🇬',
      code: 'VG',
      dial_code: '+1284',
    },
    {
      name: 'Virgin Islands, U.S.',
      flag: '🇻🇮',
      code: 'VI',
      dial_code: '+1340',
    },
    { name: 'Wallis and Futuna', flag: '🇼🇫', code: 'WF', dial_code: '+681' },
    { name: 'Wales', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', code: 'WF', dial_code: '+681' },
    { name: 'Yemen', flag: '🇾🇪', code: 'YE', dial_code: '+967' },
    { name: 'Zambia', flag: '🇿🇲', code: 'ZM', dial_code: '+260' },
    { name: 'Zimbabwe', flag: '🇿🇼', code: 'ZW', dial_code: '+263' },
  ];

export const countryList = [
  { name: 'United Kingdom', flag: '🇬🇧', code: 'GB', dial_code: '+44' },
  { name: 'United States', flag: '🇺🇸', code: 'US', dial_code: '+1' },
  { name: 'Afghanistan', flag: '🇦🇫', code: 'AF', dial_code: '+93' },
  { name: 'Åland Islands', flag: '🇦🇽', code: 'AX', dial_code: '+358' },
  { name: 'Albania', flag: '🇦🇱', code: 'AL', dial_code: '+355' },
  { name: 'Algeria', flag: '🇩🇿', code: 'DZ', dial_code: '+213' },
  { name: 'American Samoa', flag: '🇦🇸', code: 'AS', dial_code: '+1684' },
  { name: 'Andorra', flag: '🇦🇩', code: 'AD', dial_code: '+376' },
  { name: 'Angola', flag: '🇦🇴', code: 'AO', dial_code: '+244' },
  { name: 'Anguilla', flag: '🇦🇮', code: 'AI', dial_code: '+1264' },
  { name: 'Antarctica', flag: '🇦🇶', code: 'AQ', dial_code: '+672' },
  { name: 'Antigua and Barbuda', flag: '🇦🇬', code: 'AG', dial_code: '+1268' },
  { name: 'Argentina', flag: '🇦🇷', code: 'AR', dial_code: '+54' },
  { name: 'Armenia', flag: '🇦🇲', code: 'AM', dial_code: '+374' },
  { name: 'Aruba', flag: '🇦🇼', code: 'AW', dial_code: '+297' },
  { name: 'Australia', flag: '🇦🇺', code: 'AU', dial_code: '+61' },
  { name: 'Austria', flag: '🇦🇹', code: 'AT', dial_code: '+43' },
  { name: 'Azerbaijan', flag: '🇦🇿', code: 'AZ', dial_code: '+994' },
  { name: 'Bahamas', flag: '🇧🇸', code: 'BS', dial_code: '+1242' },
  { name: 'Bahrain', flag: '🇧🇭', code: 'BH', dial_code: '+973' },
  { name: 'Bangladesh', flag: '🇧🇩', code: 'BD', dial_code: '+880' },
  { name: 'Barbados', flag: '🇧🇧', code: 'BB', dial_code: '+1246' },
  { name: 'Belarus', flag: '🇧🇾', code: 'BY', dial_code: '+375' },
  { name: 'Belgium', flag: '🇧🇪', code: 'BE', dial_code: '+32' },
  { name: 'Belize', flag: '🇧🇿', code: 'BZ', dial_code: '+501' },
  { name: 'Benin', flag: '🇧🇯', code: 'BJ', dial_code: '+229' },
  { name: 'Bermuda', flag: '🇧🇲', code: 'BM', dial_code: '+1441' },
  { name: 'Bhutan', flag: '🇧🇹', code: 'BT', dial_code: '+975' },
  {
    name: 'Bolivia, Plurinational State of bolivia',
    flag: '🇧🇴',
    code: 'BO',
    dial_code: '+591',
  },
  { name: 'Bosnia and Herzegovina', flag: '🇧🇦', code: 'BA', dial_code: '+387' },
  { name: 'Botswana', flag: '🇧🇼', code: 'BW', dial_code: '+267' },
  { name: 'Bouvet Island', flag: '🇧🇻', code: 'BV', dial_code: '+47' },
  { name: 'Brazil', flag: '🇧🇷', code: 'BR', dial_code: '+55' },
  {
    name: 'British Indian Ocean Territory',
    flag: '🇮🇴',
    code: 'IO',
    dial_code: '+246',
  },
  { name: 'Brunei Darussalam', flag: '🇧🇳', code: 'BN', dial_code: '+673' },
  { name: 'Bulgaria', flag: '🇧🇬', code: 'BG', dial_code: '+359' },
  { name: 'Burkina Faso', flag: '🇧🇫', code: 'BF', dial_code: '+226' },
  { name: 'Burundi', flag: '🇧🇮', code: 'BI', dial_code: '+257' },
  { name: 'Cambodia', flag: '🇰🇭', code: 'KH', dial_code: '+855' },
  { name: 'Cameroon', flag: '🇨🇲', code: 'CM', dial_code: '+237' },
  { name: 'Canada', flag: '🇨🇦', code: 'CA', dial_code: '+1' },
  { name: 'Cape Verde', flag: '🇨🇻', code: 'CV', dial_code: '+238' },
  { name: 'Cayman Islands', flag: '🇰🇾', code: 'KY', dial_code: '+345' },
  {
    name: 'Central African Republic',
    flag: '🇨🇫',
    code: 'CF',
    dial_code: '+236',
  },
  { name: 'Chad', flag: '🇹🇩', code: 'TD', dial_code: '+235' },
  { name: 'Chile', flag: '🇨🇱', code: 'CL', dial_code: '+56' },
  { name: 'China', flag: '🇨🇳', code: 'CN', dial_code: '+86' },
  { name: 'Christmas Island', flag: '🇨🇽', code: 'CX', dial_code: '+61' },
  { name: 'Cocos (Keeling) Islands', flag: '🇨🇨', code: 'CC', dial_code: '+61' },
  { name: 'Colombia', flag: '🇨🇴', code: 'CO', dial_code: '+57' },
  { name: 'Comoros', flag: '🇰🇲', code: 'KM', dial_code: '+269' },
  { name: 'Congo', flag: '🇨🇬', code: 'CG', dial_code: '+242' },
  {
    name: 'Congo, The Democratic Republic of the Congo',
    flag: '🇨🇩',
    code: 'CD',
    dial_code: '+243',
  },
  { name: 'Cook Islands', flag: '🇨🇰', code: 'CK', dial_code: '+682' },
  { name: 'Costa Rica', flag: '🇨🇷', code: 'CR', dial_code: '+506' },
  { name: 'Cote dIvoire', flag: '🇨🇮', code: 'CI', dial_code: '+225' },
  { name: 'Croatia', flag: '🇭🇷', code: 'HR', dial_code: '+385' },
  { name: 'Cuba', flag: '🇨🇺', code: 'CU', dial_code: '+53' },
  { name: 'Cyprus', flag: '🇨🇾', code: 'CY', dial_code: '+357' },
  { name: 'Czech Republic', flag: '🇨🇿', code: 'CZ', dial_code: '+420' },
  { name: 'Denmark', flag: '🇩🇰', code: 'DK', dial_code: '+45' },
  { name: 'Djibouti', flag: '🇩🇯', code: 'DJ', dial_code: '+253' },
  { name: 'Dominica', flag: '🇩🇲', code: 'DM', dial_code: '+1767' },
  { name: 'Dominican Republic', flag: '🇩🇴', code: 'DO', dial_code: '+1849' },
  { name: 'Ecuador', flag: '🇪🇨', code: 'EC', dial_code: '+593' },
  { name: 'Egypt', flag: '🇪🇬', code: 'EG', dial_code: '+20' },
  { name: 'El Salvador', flag: '🇸🇻', code: 'SV', dial_code: '+503' },
  { name: 'Equatorial Guinea', flag: '🇬🇶', code: 'GQ', dial_code: '+240' },
  { name: 'Eritrea', flag: '🇪🇷', code: 'ER', dial_code: '+291' },
  { name: 'Estonia', flag: '🇪🇪', code: 'EE', dial_code: '+372' },
  { name: 'Ethiopia', flag: '🇪🇹', code: 'ET', dial_code: '+251' },
  {
    name: 'Falkland Islands (Malvinas)',
    flag: '🇫🇰',
    code: 'FK',
    dial_code: '+500',
  },
  { name: 'Faroe Islands', flag: '🇫🇴', code: 'FO', dial_code: '+298' },
  { name: 'Fiji', flag: '🇫🇯', code: 'FJ', dial_code: '+679' },
  { name: 'Finland', flag: '🇫🇮', code: 'FI', dial_code: '+358' },
  { name: 'France', flag: '🇫🇷', code: 'FR', dial_code: '+33' },
  { name: 'French Guiana', flag: '🇬🇫', code: 'GF', dial_code: '+594' },
  { name: 'French Polynesia', flag: '🇵🇫', code: 'PF', dial_code: '+689' },
  {
    name: 'French Southern Territories',
    flag: '🇹🇫',
    code: 'TF',
    dial_code: '+262',
  },
  { name: 'Gabon', flag: '🇬🇦', code: 'GA', dial_code: '+241' },
  { name: 'Gambia', flag: '🇬🇲', code: 'GM', dial_code: '+220' },
  { name: 'Georgia', flag: '🇬🇪', code: 'GE', dial_code: '+995' },
  { name: 'Germany', flag: '🇩🇪', code: 'DE', dial_code: '+49' },
  { name: 'Ghana', flag: '🇬🇭', code: 'GH', dial_code: '+233' },
  { name: 'Gibraltar', flag: '🇬🇮', code: 'GI', dial_code: '+350' },
  { name: 'Greece', flag: '🇬🇷', code: 'GR', dial_code: '+30' },
  { name: 'Greenland', flag: '🇬🇱', code: 'GL', dial_code: '+299' },
  { name: 'Grenada', flag: '🇬🇩', code: 'GD', dial_code: '+1473' },
  { name: 'Guadeloupe', flag: '🇬🇵', code: 'GP', dial_code: '+590' },
  { name: 'Guam', flag: '🇬🇺', code: 'GU', dial_code: '+1671' },
  { name: 'Guatemala', flag: '🇬🇹', code: 'GT', dial_code: '+502' },
  { name: 'Guernsey', flag: '🇬🇬', code: 'GG', dial_code: '+44' },
  { name: 'Guinea', flag: '🇬🇳', code: 'GN', dial_code: '+224' },
  { name: 'Guinea-Bissau', flag: '🇬🇼', code: 'GW', dial_code: '+245' },
  { name: 'Guyana', flag: '🇬🇾', code: 'GY', dial_code: '+592' },
  { name: 'Haiti', flag: '🇭🇹', code: 'HT', dial_code: '+509' },
  {
    name: 'Heard Island and Mcdonald Islands',
    flag: '🇭🇲',
    code: 'HM',
    dial_code: '+672',
  },
  {
    name: 'Holy See (Vatican City State)',
    flag: '🇻🇦',
    code: 'VA',
    dial_code: '+379',
  },
  { name: 'Honduras', flag: '🇭🇳', code: 'HN', dial_code: '+504' },
  { name: 'Hong Kong', flag: '🇭🇰', code: 'HK', dial_code: '+852' },
  { name: 'Hungary', flag: '🇭🇺', code: 'HU', dial_code: '+36' },
  { name: 'Iceland', flag: '🇮🇸', code: 'IS', dial_code: '+354' },
  { name: 'India', flag: '🇮🇳', code: 'IN', dial_code: '+91' },
  { name: 'Indonesia', flag: '🇮🇩', code: 'ID', dial_code: '+62' },
  {
    name: 'Iran, Islamic Republic of Persian Gulf',
    flag: '🇮🇷',
    code: 'IR',
    dial_code: '+98',
  },
  { name: 'Iraq', flag: '🇮🇶', code: 'IQ', dial_code: '+964' },
  { name: 'Ireland', flag: '🇮🇪', code: 'IE', dial_code: '+353' },
  { name: 'Isle of Man', flag: '🇮🇲', code: 'IM', dial_code: '+44' },
  { name: 'Israel', flag: '🇮🇱', code: 'IL', dial_code: '+972' },
  { name: 'Italy', flag: '🇮🇹', code: 'IT', dial_code: '+39' },
  { name: 'Jamaica', flag: '🇯🇲', code: 'JM', dial_code: '+1876' },
  { name: 'Japan', flag: '🇯🇵', code: 'JP', dial_code: '+81' },
  { name: 'Jersey', flag: '🇯🇪', code: 'JE', dial_code: '+44' },
  { name: 'Jordan', flag: '🇯🇴', code: 'JO', dial_code: '+962' },
  { name: 'Kazakhstan', flag: '🇰🇿', code: 'KZ', dial_code: '+7' },
  { name: 'Kenya', flag: '🇰🇪', code: 'KE', dial_code: '+254' },
  { name: 'Kiribati', flag: '🇰🇮', code: 'KI', dial_code: '+686' },
  {
    name: 'Korea, Democratic Peoples Republic of Korea',
    flag: '🇰🇵',
    code: 'KP',
    dial_code: '+850',
  },
  {
    name: 'Korea, Republic of South Korea',
    flag: '🇰🇷',
    code: 'KR',
    dial_code: '+82',
  },
  { name: 'Kosovo', flag: '🇽🇰', code: 'XK', dial_code: '+383' },
  { name: 'Kuwait', flag: '🇰🇼', code: 'KW', dial_code: '+965' },
  { name: 'Kyrgyzstan', flag: '🇰🇬', code: 'KG', dial_code: '+996' },
  { name: 'Laos', flag: '🇱🇦', code: 'LA', dial_code: '+856' },
  { name: 'Latvia', flag: '🇱🇻', code: 'LV', dial_code: '+371' },
  { name: 'Lebanon', flag: '🇱🇧', code: 'LB', dial_code: '+961' },
  { name: 'Lesotho', flag: '🇱🇸', code: 'LS', dial_code: '+266' },
  { name: 'Liberia', flag: '🇱🇷', code: 'LR', dial_code: '+231' },
  { name: 'Libyan Arab Jamahiriya', flag: '🇱🇾', code: 'LY', dial_code: '+218' },
  { name: 'Liechtenstein', flag: '🇱🇮', code: 'LI', dial_code: '+423' },
  { name: 'Lithuania', flag: '🇱🇹', code: 'LT', dial_code: '+370' },
  { name: 'Luxembourg', flag: '🇱🇺', code: 'LU', dial_code: '+352' },
  { name: 'Macao', flag: '🇲🇴', code: 'MO', dial_code: '+853' },
  { name: 'Macedonia', flag: '🇲🇰', code: 'MK', dial_code: '+389' },

  { name: 'Macedonia', flag: '🇲🇰', code: 'MK', dial_code: '+389' },
  { name: 'Madagascar', flag: '🇲🇬', code: 'MG', dial_code: '+261' },
  { name: 'Malawi', flag: '🇲🇼', code: 'MW', dial_code: '+265' },
  { name: 'Malaysia', flag: '🇲🇾', code: 'MY', dial_code: '+60' },
  { name: 'Maldives', flag: '🇲🇻', code: 'MV', dial_code: '+960' },
  { name: 'Mali', flag: '🇲🇱', code: 'ML', dial_code: '+223' },
  { name: 'Malta', flag: '🇲🇹', code: 'MT', dial_code: '+356' },
  { name: 'Marshall Islands', flag: '🇲🇭', code: 'MH', dial_code: '+692' },
  { name: 'Martinique', flag: '🇲🇶', code: 'MQ', dial_code: '+596' },
  { name: 'Mauritania', flag: '🇲🇷', code: 'MR', dial_code: '+222' },
  { name: 'Mauritius', flag: '🇲🇺', code: 'MU', dial_code: '+230' },
  { name: 'Mayotte', flag: '🇾🇹', code: 'YT', dial_code: '+262' },
  { name: 'Mexico', flag: '🇲🇽', code: 'MX', dial_code: '+52' },
  {
    name: 'Micronesia, Federated States of Micronesia',
    flag: '🇫🇲',
    code: 'FM',
    dial_code: '+691',
  },
  { name: 'Moldova', flag: '🇲🇩', code: 'MD', dial_code: '+373' },
  { name: 'Monaco', flag: '🇲🇨', code: 'MC', dial_code: '+377' },
  { name: 'Mongolia', flag: '🇲🇳', code: 'MN', dial_code: '+976' },
  { name: 'Montenegro', flag: '🇲🇪', code: 'ME', dial_code: '+382' },
  { name: 'Montserrat', flag: '🇲🇸', code: 'MS', dial_code: '+1664' },
  { name: 'Morocco', flag: '🇲🇦', code: 'MA', dial_code: '+212' },
  { name: 'Mozambique', flag: '🇲🇿', code: 'MZ', dial_code: '+258' },
  { name: 'Myanmar', flag: '🇲🇲', code: 'MM', dial_code: '+95' },
  { name: 'Namibia', flag: '🇳🇦', code: 'NA', dial_code: '+264' },
  { name: 'Nauru', flag: '🇳🇷', code: 'NR', dial_code: '+674' },
  { name: 'Nepal', flag: '🇳🇵', code: 'NP', dial_code: '+977' },
  { name: 'Netherlands', flag: '🇳🇱', code: 'NL', dial_code: '+31' },
  { name: 'Netherlands Antilles', flag: '', code: 'AN', dial_code: '+599' },
  { name: 'New Caledonia', flag: '🇳🇨', code: 'NC', dial_code: '+687' },
  { name: 'New Zealand', flag: '🇳🇿', code: 'NZ', dial_code: '+64' },
  { name: 'Nicaragua', flag: '🇳🇮', code: 'NI', dial_code: '+505' },
  { name: 'Niger', flag: '🇳🇪', code: 'NE', dial_code: '+227' },
  { name: 'Nigeria', flag: '🇳🇬', code: 'NG', dial_code: '+234' },
  { name: 'Niue', flag: '🇳🇺', code: 'NU', dial_code: '+683' },
  { name: 'Norfolk Island', flag: '🇳🇫', code: 'NF', dial_code: '+672' },
  {
    name: 'Northern Mariana Islands',
    flag: '🇲🇵',
    code: 'MP',
    dial_code: '+1670',
  },
  { name: 'Norway', flag: '🇳🇴', code: 'NO', dial_code: '+47' },
  { name: 'Oman', flag: '🇴🇲', code: 'OM', dial_code: '+968' },
  { name: 'Pakistan', flag: '🇵🇰', code: 'PK', dial_code: '+92' },
  { name: 'Palau', flag: '🇵🇼', code: 'PW', dial_code: '+680' },
  {
    name: 'Palestinian Territory, Occupied',
    flag: '🇵🇸',
    code: 'PS',
    dial_code: '+970',
  },
  { name: 'Panama', flag: '🇵🇦', code: 'PA', dial_code: '+507' },
  { name: 'Papua New Guinea', flag: '🇵🇬', code: 'PG', dial_code: '+675' },
  { name: 'Paraguay', flag: '🇵🇾', code: 'PY', dial_code: '+595' },
  { name: 'Peru', flag: '🇵🇪', code: 'PE', dial_code: '+51' },
  { name: 'Philippines', flag: '🇵🇭', code: 'PH', dial_code: '+63' },
  { name: 'Pitcairn', flag: '🇵🇳', code: 'PN', dial_code: '+64' },
  { name: 'Poland', flag: '🇵🇱', code: 'PL', dial_code: '+48' },
  { name: 'Portugal', flag: '🇵🇹', code: 'PT', dial_code: '+351' },
  { name: 'Puerto Rico', flag: '🇵🇷', code: 'PR', dial_code: '+1939' },
  { name: 'Qatar', flag: '🇶🇦', code: 'QA', dial_code: '+974' },
  { name: 'Romania', flag: '🇷🇴', code: 'RO', dial_code: '+40' },
  { name: 'Russia', flag: '🇷🇺', code: 'RU', dial_code: '+7' },
  { name: 'Rwanda', flag: '🇷🇼', code: 'RW', dial_code: '+250' },
  { name: 'Reunion', flag: '🇷🇪', code: 'RE', dial_code: '+262' },
  { name: 'Saint Barthelemy', flag: '🇧🇱', code: 'BL', dial_code: '+590' },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    flag: '🇸🇭',
    code: 'SH',
    dial_code: '+290',
  },
  { name: 'Saint Kitts and Nevis', flag: '🇰🇳', code: 'KN', dial_code: '+1869' },
  { name: 'Saint Lucia', flag: '🇱🇨', code: 'LC', dial_code: '+1758' },
  { name: 'Saint Martin', flag: '🇲🇫', code: 'MF', dial_code: '+590' },
  {
    name: 'Saint Pierre and Miquelon',
    flag: '🇵🇲',
    code: 'PM',
    dial_code: '+508',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    flag: '🇻🇨',
    code: 'VC',
    dial_code: '+1784',
  },
  { name: 'Samoa', flag: '🇼🇸', code: 'WS', dial_code: '+685' },
  { name: 'San Marino', flag: '🇸🇲', code: 'SM', dial_code: '+378' },
  { name: 'Sao Tome and Principe', flag: '🇸🇹', code: 'ST', dial_code: '+239' },
  { name: 'Saudi Arabia', flag: '🇸🇦', code: 'SA', dial_code: '+966' },
  { name: 'Senegal', flag: '🇸🇳', code: 'SN', dial_code: '+221' },
  { name: 'Serbia', flag: '🇷🇸', code: 'RS', dial_code: '+381' },
  { name: 'Seychelles', flag: '🇸🇨', code: 'SC', dial_code: '+248' },
  { name: 'Sierra Leone', flag: '🇸🇱', code: 'SL', dial_code: '+232' },
  { name: 'Singapore', flag: '🇸🇬', code: 'SG', dial_code: '+65' },
  { name: 'Slovakia', flag: '🇸🇰', code: 'SK', dial_code: '+421' },
  { name: 'Slovenia', flag: '🇸🇮', code: 'SI', dial_code: '+386' },
  { name: 'Solomon Islands', flag: '🇸🇧', code: 'SB', dial_code: '+677' },
  { name: 'Somalia', flag: '🇸🇴', code: 'SO', dial_code: '+252' },
  { name: 'South Africa', flag: '🇿🇦', code: 'ZA', dial_code: '+27' },
  { name: 'South Sudan', flag: '🇸🇸', code: 'SS', dial_code: '+211' },
  {
    name: 'South Georgia and the South Sandwich Islands',
    flag: '🇬🇸',
    code: 'GS',
    dial_code: '+500',
  },
  { name: 'Spain', flag: '🇪🇸', code: 'ES', dial_code: '+34' },
  { name: 'Sri Lanka', flag: '🇱🇰', code: 'LK', dial_code: '+94' },
  { name: 'Sudan', flag: '🇸🇩', code: 'SD', dial_code: '+249' },
  { name: 'Suriname', flag: '🇸🇷', code: 'SR', dial_code: '+597' },
  { name: 'Svalbard and Jan Mayen', flag: '🇸🇯', code: 'SJ', dial_code: '+47' },
  { name: 'Eswatini', flag: '🇸🇿', code: 'SZ', dial_code: '+268' },
  { name: 'Sweden', flag: '🇸🇪', code: 'SE', dial_code: '+46' },
  { name: 'Switzerland', flag: '🇨🇭', code: 'CH', dial_code: '+41' },
  { name: 'Syrian Arab Republic', flag: '🇸🇾', code: 'SY', dial_code: '+963' },
  { name: 'Taiwan', flag: '🇹🇼', code: 'TW', dial_code: '+886' },
  { name: 'Tajikistan', flag: '🇹🇯', code: 'TJ', dial_code: '+992' },
  {
    name: 'Tanzania, United Republic of Tanzania',
    flag: '🇹🇿',
    code: 'TZ',
    dial_code: '+255',
  },
  { name: 'Thailand', flag: '🇹🇭', code: 'TH', dial_code: '+66' },
  { name: 'Timor-Leste', flag: '🇹🇱', code: 'TL', dial_code: '+670' },
  { name: 'Togo', flag: '🇹🇬', code: 'TG', dial_code: '+228' },
  { name: 'Tokelau', flag: '🇹🇰', code: 'TK', dial_code: '+690' },
  { name: 'Tonga', flag: '🇹🇴', code: 'TO', dial_code: '+676' },
  { name: 'Trinidad and Tobago', flag: '🇹🇹', code: 'TT', dial_code: '+1868' },
  { name: 'Tunisia', flag: '🇹🇳', code: 'TN', dial_code: '+216' },
  { name: 'Turkey', flag: '🇹🇷', code: 'TR', dial_code: '+90' },
  { name: 'Turkmenistan', flag: '🇹🇲', code: 'TM', dial_code: '+993' },
  {
    name: 'Turks and Caicos Islands',
    flag: '🇹🇨',
    code: 'TC',
    dial_code: '+1649',
  },
  { name: 'Tuvalu', flag: '🇹🇻', code: 'TV', dial_code: '+688' },
  { name: 'Uganda', flag: '🇺🇬', code: 'UG', dial_code: '+256' },
  { name: 'Ukraine', flag: '🇺🇦', code: 'UA', dial_code: '+380' },
  { name: 'United Arab Emirates', flag: '🇦🇪', code: 'UA', dial_code: '+971' },
  { name: 'Uruguay', flag: '🇺🇾', code: 'UY', dial_code: '+598' },
  { name: 'Uzbekistan', flag: '🇺🇿', code: 'UZ', dial_code: '+998' },
  { name: 'Vanuatu', flag: '🇻🇺', code: 'VU', dial_code: '+678' },
  {
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    flag: '🇻🇪',
    code: 'VE',
    dial_code: '+58',
  },
  { name: 'Vietnam', flag: '🇻🇳', code: 'VN', dial_code: '+84' },
  {
    name: 'Virgin Islands, British',
    flag: '🇻🇬',
    code: 'VG',
    dial_code: '+1284',
  },
  { name: 'Virgin Islands, U.S.', flag: '🇻🇮', code: 'VI', dial_code: '+1340' },
  { name: 'Wallis and Futuna', flag: '🇼🇫', code: 'WF', dial_code: '+681' },
  { name: 'Yemen', flag: '🇾🇪', code: 'YE', dial_code: '+967' },
  { name: 'Zambia', flag: '🇿🇲', code: 'ZM', dial_code: '+260' },
  { name: 'Zimbabwe', flag: '🇿🇼', code: 'ZW', dial_code: '+263' },
];
