import React from 'react';
import {
  FaFilePdf,
  FaHandsHelping,
  FaRupeeSign,
  FaSignal,
  FaUser,
  FaLinkedinIn,
  FaRegHandshake,
  FaRegHeart,
  FaStar,
  FaFacebookMessenger,
  FaSms,
} from 'react-icons/fa';
import { IoLogoWhatsapp } from 'react-icons/io';
import { FiCheckCircle, FiMapPin, FiUsers } from 'react-icons/fi';
import { TbCalendarStats, TbCameraPlus } from 'react-icons/tb';
import { TfiViewList } from 'react-icons/tfi';
import { LuCopyCheck } from 'react-icons/lu';
import {
  BsCalendarPlus,
  BsCheckLg,
  BsChevronDown,
  BsChevronLeft,
  BsChevronRight,
  BsDownload,
  BsEmojiSmile,
  BsFillCheckCircleFill,
  BsTag,
  BsThreeDotsVertical,
  BsArrowLeft,
  BsArrowRight,
  BsThreeDots,
  BsGenderMale,
  BsPerson,
  BsGraphUpArrow,
  BsCalendarX,
  BsApple,
  BsDiscord,
  BsQrCode,
  BsPeople,
  BsShareFill,
  BsRobot,
  BsChevronUp,
} from 'react-icons/bs';
import {
  BiLogOutCircle,
  BiDollarCircle,
  BiInfoCircle,
  BiPlus,
  BiMinus,
  BiSearch,
  BiHomeAlt2,
  BiCalendarAlt,
  BiWallet,
  BiLogoPlayStore,
  BiLogoTelegram,
  BiLogoLinkedin,
  BiLogoYoutube,
  BiPowerOff,
  BiLogoFacebook,
  BiSolidDownArrow,
} from 'react-icons/bi';
import {
  AiFillCustomerService,
  AiOutlineTwitter,
  AiFillEye,
  AiFillEyeInvisible,
  AiFillLayout,
  AiFillStar,
  AiOutlineSetting,
  AiOutlineStar,
  AiOutlineUnorderedList,
  AiOutlineUsergroupAdd,
  AiOutlineCloseCircle,
  AiFillInstagram,
  AiOutlineClockCircle,
} from 'react-icons/ai';
import {
  MdClose,
  MdDashboard,
  MdDelete,
  MdEdit,
  MdOutlineAnalytics,
  MdOutlineContentCopy,
  MdPublishedWithChanges,
  MdRocketLaunch,
  MdOutlineWorkOutline,
  MdOutlineOtherHouses,
  MdDateRange,
  MdAttachMoney,
  MdFavoriteBorder,
} from 'react-icons/md';

import { ImQuotesLeft } from 'react-icons/im';
import {
  HiDocumentReport,
  HiMenu,
  HiOutlineDocumentReport,
} from 'react-icons/hi';
import { GoVerified } from 'react-icons/go';
import { RiSecurePaymentLine, RiFlashlightLine } from 'react-icons/ri';

import LiveIcon from '@components/SvgCompass/LiveIcon';

export const reactIcons = {
  arrowup: <BsChevronUp />,
  livenow: <LiveIcon />,
  bot: <BsRobot />,
  share: <BsShareFill />,
  money: <MdAttachMoney />,
  people: <BsPeople />,
  trading: <BsGraphUpArrow />,
  power: <BiPowerOff />,
  apple: <BsApple />,
  star2: <FaStar />,
  playstore: <BiLogoPlayStore />,
  offline: <BsCalendarX />,
  close1: <AiOutlineCloseCircle />,
  user: <FaUser />,
  logout: <BiLogOutCircle />,
  dollar: <BiDollarCircle />,
  list: <AiOutlineUnorderedList />,
  arrowleft: <BsChevronLeft />,
  arrowright: <BsChevronRight />,
  arrowdown: <BsChevronDown />,
  success: <BsFillCheckCircleFill />,
  pdf: <FaFilePdf />,
  info: <BiInfoCircle />,
  dashboard: <MdDashboard />,
  layouts: <AiFillLayout />,
  reports: <HiDocumentReport />,
  verify: <GoVerified />,
  publish: <MdPublishedWithChanges />,
  plus: <BiPlus />,
  minus: <BiMinus />,
  rupee: <FaRupeeSign />,
  copy: <MdOutlineContentCopy />,
  copied: <LuCopyCheck />,
  edit: <MdEdit />,
  delete: <MdDelete />,
  search: <BiSearch />,
  news: <MdRocketLaunch />,
  home: <BiHomeAlt2 />,
  calendar: <BiCalendarAlt />,
  sales: <BsTag />,
  customer: <BsEmojiSmile />,
  analytics: <MdOutlineAnalytics />,
  staff: <FiUsers />,
  setup: <AiOutlineSetting />,
  services: <AiFillCustomerService />,
  empty: <FaSignal />,
  timeCalendar: <TbCalendarStats />,
  download: <BsDownload />,
  close: <MdClose />,
  camera: <TbCameraPlus />,
  listNestedBox: <AiOutlineUnorderedList />,
  listBox: <TfiViewList />,
  menu: <HiMenu />,
  threeDots: <BsThreeDotsVertical />,
  eyeslash: <AiFillEyeInvisible />,
  eyes: <AiFillEye />,
  location: <FiMapPin />,
  successCheck: <FiCheckCircle />,
  check: <BsCheckLg />,
  importUser: <AiOutlineUsergroupAdd />,
  addCalendar: <BsCalendarPlus />,
  helpCenter: <FaHandsHelping />,
  star: <AiOutlineStar />,
  fillstar: <AiFillStar />,
  work: <MdOutlineWorkOutline />,
  other: <MdOutlineOtherHouses />,
  left: <BsArrowLeft />,
  right: <BsArrowRight />,
  dot3: <BsThreeDots />,
  wallet: <BiWallet />,
  date: <MdDateRange />,
  insta: <AiFillInstagram />,
  facebook: <BiLogoFacebook />,
  linkdin: <FaLinkedinIn />,
  twitter: <AiOutlineTwitter />,
  queto: <ImQuotesLeft />,
  clock: <AiOutlineClockCircle />,
  paybyapp: <RiSecurePaymentLine />,
  male: <BsGenderMale />,
  flash: <RiFlashlightLine />,
  hands: <FaRegHandshake />,
  person: <BsPerson />,
  fav: <MdFavoriteBorder />,
  heart: <FaRegHeart />,
  telegram: <BiLogoTelegram />,
  discord: <BsDiscord />,
  linkedin: <BiLogoLinkedin />,
  youtube: <BiLogoYoutube />,
  qrcode: <BsQrCode />,
  arrowdownFill: <BiSolidDownArrow />,
  portfolio: <HiOutlineDocumentReport />,
  whatsapp: <IoLogoWhatsapp />,
  messenger: <FaFacebookMessenger />,
  sms: <FaSms />,
};
