export const images = {
  football: '/images/bikoicon/football.png',
  bikoSport: '/images/bikoicon/bikosports.png',
  user: '/images/bikoicon/user.png',
  homeIcon: '/images/bikoicon/home.png',
  homeIconActive: '/images/bikoicon/home.png',
  liveNowIcon: '/images/bikoicon/livenow.svg',
  liveNowIconActive: '/images/bikoicon/livenowwhite.png',
  upcomingIcon: '/images/bikoicon/upcoming.png',
  upcomingIconActive: '/images/bikoicon/upcomingwhite.png',
  virtualsportIcon: '/images/bikoicon/virtual-sport.png',
  virtualsportIconActive: '/images/bikoicon/virtualsportwhite.png',
  jackpotIcon: '/images/bikoicon/jackpot.png',
  jackpotIconActive: '/images/bikoicon/jackpotwhite.png',
  popularIcon: '/images/bikoicon/popular.png',
  popularIconActive: '/images/bikoicon/popularwhite.png',
  soccerIcon: '/images/bikoicon/',
  soccerIconActive: '/images/bikoicon/',
  basketballIcon: '/images/bikoicon/',
  basketballIconActive: '/images/bikoicon/',
  boxingIcon: '/images/bikoicon/',
  boxingIconActive: '/images/bikoicon/',
  rugbyIcon: '/images/bikoicon/',
  rugbyIconActive: '/images/bikoicon/',
  cricketIcon: '/images/bikoicon/',
  cricketIconActive: '/images/bikoicon/',
};
